// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2yLUcR2OKqU5P6sVR_wlc-9iK5JG2kA',
    appId: '1:1076138635257:android:4b7fc7cf78707addea9728',
    messagingSenderId: '1076138635257',
    projectId: 'piwcstoneyburn-2aa73',
    storageBucket: 'piwcstoneyburn-2aa73.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSXkdlEHWOqD_0gyKmgpmNXfkNa2qT68',
    appId: '1:1076138635257:ios:31458dad4e8682ebea9728',
    messagingSenderId: '1076138635257',
    projectId: 'piwcstoneyburn-2aa73',
    storageBucket: 'piwcstoneyburn-2aa73.firebasestorage.app',
    iosBundleId: 'com.piwc.stoneyburn',
  );
}
